### ISSUE TITLE
"What 0 Pussy does to a mf" is broken

### ISSUE THREAD

**Issue by suckfingerduckkong** [extraes/BW-Chaos#3]
i have not only disabled this effect, but it continues to randomly activate despite having the voting system turned on. every time it activates, i lose permanent control over my arms until the timer is up, then once it is up i gain that control back but i am forced into the ground in a crouch. i cannot move at all, killing myself does not work, and no clipping does not work either. it forces me into a crouched position far lower than what the controllers allow for, and i have to restart the entire game when this effect comes on. please fix this

**Comment by extraes** [comment]
pretty sure 2.2.0 fixes what youre talking about
send a log though

**Comment by extraes** [comment]
you are right though the disabled effect array doesnt work, ill wrap up what im working on and push 2.2.1 out the door as soon as possible

**Comment by extraes** [comment]
fixed in 2.2.1
